'use strict';
/** 
 * @author github.com/tintinweb
 * @license MIT
 * 
 * Syntax highlighting grammar is based on Python from: https://raw.githubusercontent.com/Microsoft/vscode/master/extensions/python/syntaxes/MagicPython.tmLanguage.json (MIT)
 * The grammar is generated by merging Python's TextMate grammar with Vyper-specific language features.
 * */

/** imports */
const vscode = require("vscode");

const settings = require("./settings");
const mod_deco = require("./features/deco.js");
const mod_hover = require("./features/hover/hover.js");
const mod_lsp = require("./features/lsp.js");
/** global vars */
var activeEditor;



/** event funcs */

async function onDidChange(event) {
    if (vscode.window.activeTextEditor.document.languageId != settings.LANGUAGE_ID) {
        return;
    }

    mod_deco.decorateWords(activeEditor, [
        {
            regex: "^@\\b(public|nonpayable|payable|external|deploy)\\b",
            captureGroup: 0,
        },
        {
            regex: "\\b(send|raw_call|selfdestruct|create_forwarder_to|create_minimal_proxy_to|create_copy_of|create_from_blueprint)\\b",
            captureGroup: 0,
            hoverMessage: "❗**potentially unsafe** lowlevel call"
        },
        {
            regex: "\\b(extcall|staticcall)\\b",
            captureGroup: 0,
        },
    ], mod_deco.styles.foreGroundWarning);
    mod_deco.decorateWords(activeEditor, [
        {
            regex: "\\b(\\.balance|msg\\.[\\w]+|block\\.[\\w]+)\\b",
            captureGroup: 0,
        }
    ], mod_deco.styles.foreGroundInfoUnderline);
    mod_deco.decorateWords(activeEditor, [
        {
            regex: "^@\\b(nonreentrant|internal|view|pure)\\b",
            captureGroup: 0,
        },
    ], mod_deco.styles.foreGroundOk);
    mod_deco.decorateWords(activeEditor, [
        {
            regex: "\\b(log)\\.",
            captureGroup: 1,
        },
        {
            regex: "\\b(clear)\\b\\(",
            captureGroup: 1,
        },
    ], mod_deco.styles.foreGroundNewEmit);
    mod_deco.decorateWords(activeEditor, [
        {
            regex: "\\b(__init__|__default__)\\b",
            captureGroup: 0,
        },
    ], mod_deco.styles.boldUnderline);
}
function onInitModules(context, type) {
    mod_hover.init(context, type);

    // Register restart LSP server command (register before LSP init so it's always available)
    const restartCommand = vscode.commands.registerCommand('vyper.restartLspServer', async () => {
        try {
            await mod_lsp.restart(context, type);
            vscode.window.showInformationMessage('Vyper LSP Server restarted successfully');
        } catch (error) {
            vscode.window.showErrorMessage(`Failed to restart Vyper LSP Server: ${error.message}`);
        }
    });
    context.subscriptions.push(restartCommand);

    // Initialize LSP (after command registration so command is always available even if LSP fails)
    try {
        mod_lsp.init(context, type);
    } catch (error) {
        console.error('Failed to initialize LSP:', error);
        vscode.window.showWarningMessage('Vyper LSP failed to initialize. Some features may not be available.');
    }
}

function onActivate(context) {

    const active = vscode.window.activeTextEditor;
    activeEditor = active;

    registerDocType(settings.LANGUAGE_ID);

    function registerDocType(type) {
        // taken from: https://github.com/Microsoft/vscode/blob/master/extensions/python/src/pythonMain.ts ; slightly modified
        // autoindent while typing
        vscode.languages.setLanguageConfiguration(type, {
            onEnterRules: [
                {
                    beforeText: /^\s*(?:struct|flag|event|interface|def|class|for|if|elif|else).*?:\s*$/,
                    action: { indentAction: vscode.IndentAction.Indent }
                }
            ]
        });

        // Initialize modules including LSP
        onInitModules(context, type);
        onDidChange();

        /** event setup */
        /***** OnChange */
        vscode.window.onDidChangeActiveTextEditor(editor => {
            activeEditor = editor;
            if (editor) {
                onDidChange();
            }
        }, null, context.subscriptions);
        /***** OnChange */
        vscode.workspace.onDidChangeTextDocument(event => {
            if (activeEditor && event.document === activeEditor.document) {
                onDidChange(event);
            }
        }, null, context.subscriptions);

    }
}

// Add deactivate function to properly stop the LSP client
function onDeactivate() {
    const client = mod_lsp.getClient();
    if (client) {
        return client.stop();
    }
}

/* exports */
exports.activate = onActivate;
exports.deactivate = onDeactivate;
